### ISSUE TITLE
Конкатенация в URL

### ISSUE THREAD

**Issue by anry-das** [bi-te/bMovieSearch#11]
Конкатенаций следует избегать.
В **OMDBService.getMovieByTitle** и  **OMDBService.getMovieById** формирование URL можно заменить на **UriComponentsBuilder** (как например [тут](https://stackoverflow.com/questions/35998790/resttemplate-how-to-send-url-and-query-parameters-together))

**Comment by bi-te** [comment]
26c96e6fdb622be2fb8ce62d2fb2ab8c4a15e193
