### ISSUE TITLE
Функционал MovieToWordDownloader

### ISSUE THREAD

**Issue by anry-das** [bi-te/bMovieSearch#5]
Функционал MovieToWordDownloader очень напоминает конвертер. Возможно его целесообразнее оформить именно в виде конвертера (интерфейс Converter<S,T>).

**Comment by bi-te** [comment]
Я решил не оформлять его в  виде конвертера, так как логически его задача состоит не в преобразовании объкта одного класса в другой, а в большей степени загрузке данных в файл ворд.

**Comment by bi-te** [comment]
798a4b079abc5bc78ac622ea2ecb066e06641f31
