### ISSUE TITLE
Добавить шаблон Word

### ISSUE THREAD

**Issue by anry-das** [bi-te/bMovieSearch#7]
Необходимо добавить шаблон Word (согласно требованиям)

**Comment by anry-das** [comment]
В шаблоне можно использовать макро символы, например:

**Comment by bi-te** [comment]
798a4b079abc5bc78ac622ea2ecb066e06641f31

**Comment by anry-das** [comment]
зачем
private String template = "MovieSearchTemplate.docx";
если шаблон также есть и в application.properties?
Здесь правильно использовать @Value
